services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: final_production
    container_name: travel-app-container
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: node server.js
    restart: always
