version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: travel-app-dev
    ports:
      - "8081:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=3000
    command: npm run dev
    restart: always

